export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    GET_LIST_FRIEND_SUCCESS: 'GET_LIST_FRIEND_SUCCESS',
    GET_LIST_FRIEND_FAIL: 'GET_LIST_FRIEND_FAIL',
    LOGOUT: 'LOGOUT',
};
