import {
    loginSuccess,
    loginFail,
    registerSuccess,
    registerFail,
    getListFriendSuccess,
    getListFriendFail,
    updateLastMessage,
    updateUserInfoSuccess,
    updateUserInfoFail,
    uploadAvatarSuccess,
    uploadAvatarFail,
    getListFriendRequestSuccess,
    getListFriendRequestFail,
    acceptFriendSuccess,
    acceptFriendFail,
    logout,
    removeFriendRequest,
    getGifItems,
    updateFriendShip,
    changeLanguage,
    changeOnline,
} from './userReducer/Action';
import { connectSuccess, connectFail, disconnect } from './stompReducer/Action';
import { getGenres, addHotMovies, addMovies, addTrendingMovies, addUsers } from './movieReducer/Action';

export {
    loginSuccess,
    loginFail,
    registerSuccess,
    registerFail,
    getListFriendSuccess,
    getListFriendFail,
    updateUserInfoSuccess,
    updateUserInfoFail,
    uploadAvatarSuccess,
    uploadAvatarFail,
    getListFriendRequestSuccess,
    getListFriendRequestFail,
    updateLastMessage,
    acceptFriendSuccess,
    acceptFriendFail,
    logout,
    connectSuccess,
    connectFail,
    disconnect,
    removeFriendRequest,
    getGifItems,
    updateFriendShip,
    changeLanguage,
    changeOnline,
    getGenres,
    addHotMovies,
    addMovies,
    addTrendingMovies,
    addUsers,
};

export { default } from './Reducers';
